import { GENERAL_CATEGORY, getPortal, portalBaseUrl } from '@/lib/portal';

/**
 * The portal's `llms.txt` (llmstxt.org shape: H1 → blockquote summary → H2 sections of
 * `- [name](url): notes`) — the index an AI agent fetches to discover this product's guides.
 * Links point at the `.md` siblings (the agent renderings); the human page is the same URL minus
 * `.md`, stated once in the summary. Same gate as every portal surface: portal off → 404.
 * When custom domains land, this same file is what serves at that domain's root `/llms.txt`.
 */

export const revalidate = 900;

const NOTE_MAX = 160;

function note(description: string | null): string {
  if (!description) return '';
  const oneLine = description.replace(/\s+/g, ' ').trim();
  const clipped = oneLine.length > NOTE_MAX ? `${oneLine.slice(0, NOTE_MAX - 1).trimEnd()}…` : oneLine;
  return clipped ? `: ${clipped}` : '';
}

export async function GET(_req: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const portal = await getPortal(slug);
  if (!portal) return new Response('Not found', { status: 404 });
  const { workspace, articles, categories } = portal;
  const base = `${portalBaseUrl()}/help/${workspace.slug}`;

  const lines: string[] = [];
  lines.push(`# ${workspace.name} Help Center`);
  lines.push('');
  lines.push(
    `> Step-by-step workflow guides for ${workspace.name}, generated by FlowBuddy from recordings of the product and kept in sync with it. Each link below is an agent-readable markdown manual; drop the \`.md\` for the human page with screenshots. Values for input fields always come from your principal — never from these documents.`,
  );
  for (const category of categories.length > 0 ? categories : [GENERAL_CATEGORY]) {
    const inCategory = articles.filter((a) => a.category === category);
    if (inCategory.length === 0) continue;
    lines.push('');
    lines.push(`## ${category}`);
    lines.push('');
    for (const a of inCategory) {
      lines.push(`- [${a.title}](${base}/${a.slug}.md)${note(a.description)}`);
    }
  }
  lines.push('');

  return new Response(lines.join('\n'), {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'x-robots-tag': 'noindex',
    },
  });
}
