import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalPage, Section } from '@/components/legal-page';

export const metadata: Metadata = {
  title: 'Terms of Service · FlowBuddy',
  description:
    'The terms that govern your use of FlowBuddy Studio, the FlowBuddy Recorder and the embeddable FlowBuddy copilot.',
};

// Where legal notices should be sent.
const CONTACT_EMAIL = 'founder@flowbuddyai.com';
const LAST_UPDATED = 'August 23, 2026';

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <p className="text-[14px] leading-relaxed text-muted-foreground">
        These Terms of Service (&ldquo;Terms&rdquo;) are an agreement between you and
        FlowBuddy (&ldquo;FlowBuddy&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). They govern your
        use of the <strong className="text-ink">FlowBuddy Studio</strong> web app, the{' '}
        <strong className="text-ink">FlowBuddy Recorder</strong> browser extension, the
        embeddable FlowBuddy copilot and any related services (together, the
        &ldquo;Service&rdquo;). By creating an account or using the Service you agree to these
        Terms and to our{' '}
        <Link href="/privacy" className="font-medium text-primary underline-offset-4 hover:underline">
          Privacy Policy
        </Link>
        . If you are using the Service on behalf of a company, you represent that you have
        authority to bind that company, and &ldquo;you&rdquo; refers to it.
      </p>

      <Section title="1. The Service">
        <p>
          FlowBuddy lets you record narrated walkthroughs of your own product, turns those
          recordings into a knowledge base that you review and approve, and provides an
          in-app copilot that answers your users&rsquo; questions from the knowledge you have
          approved. Optional capabilities — such as guided walkthroughs and an acting
          &ldquo;AI Agent&rdquo; mode — are described in the product and may be subject to
          additional terms you accept before enabling them.
        </p>
        <p>
          The Service is provided as an early-access product. Features may change, be added or
          be removed as we develop it.
        </p>
      </Section>

      <Section title="2. Accounts">
        <ul className="ml-5 list-disc space-y-1.5">
          <li>You must be at least 18 years old and able to form a binding contract.</li>
          <li>
            You must provide accurate account information and keep your credentials
            confidential. You are responsible for all activity under your account.
          </li>
          <li>
            Notify us promptly at the address below if you believe your account has been
            compromised.
          </li>
        </ul>
      </Section>

      <Section title="3. Your content">
        <p>
          &ldquo;Your Content&rdquo; means everything you submit to the Service — recordings
          (screenshots, narration audio, interaction events), the knowledge derived from
          them, edits you make in Studio, your workspace settings, and the questions your
          end users ask the copilot.
        </p>
        <ul className="ml-5 list-disc space-y-1.5">
          <li>
            <strong className="text-ink">You own Your Content.</strong> You grant us a
            worldwide, non-exclusive licence to host, process, display and transmit it solely
            to provide, secure and improve the Service for you.
          </li>
          <li>
            You are responsible for Your Content and for having the rights to record the
            product you record and to share what your recordings contain. Do not record
            pages that display third-party personal data, credentials, payment details or
            other confidential information you are not entitled to share.
          </li>
          <li>
            You decide what the copilot may use. Only knowledge you have explicitly approved
            in Studio is served to your end users; you can retire or edit it at any time.
          </li>
        </ul>
      </Section>

      <Section title="4. AI-generated output">
        <p>
          The knowledge base, copilot answers and any agent actions are generated by machine
          learning models from Your Content. They may be incomplete, out of date or wrong.
          You are responsible for reviewing generated knowledge before approving it, for the
          answers your copilot gives your users, and — where you enable an acting mode — for
          the actions it performs inside your product. FlowBuddy does not warrant the
          accuracy of any generated output.
        </p>
      </Section>

      <Section title="5. Acceptable use">
        <p>You agree not to:</p>
        <ul className="ml-5 list-disc space-y-1.5">
          <li>use the Service to break the law or infringe anyone&rsquo;s rights;</li>
          <li>
            record, upload or distribute content that is unlawful, harmful, deceptive or that
            you do not have the right to share;
          </li>
          <li>
            probe, disrupt or overload the Service, circumvent its limits or access it by any
            means other than the interfaces we provide;
          </li>
          <li>reverse-engineer the Service except where the law permits it;</li>
          <li>resell or sublicense the Service without our written consent; or</li>
          <li>
            embed the copilot on a site or product you do not own or have permission to
            modify.
          </li>
        </ul>
      </Section>

      <Section title="6. The embeddable copilot">
        <p>
          When you install the copilot on your product, you are responsible for disclosing
          its use to your end users as required by applicable law, for any notices or
          consents their use of it needs, and for the terms under which your end users use
          your product. We process end-user questions on your behalf to provide the Service.
        </p>
      </Section>

      <Section title="7. Fees">
        <p>
          The Service is currently offered free of charge during early access. We may
          introduce paid plans or usage-based charges in the future; we will give you
          reasonable notice and you will not be charged without agreeing to the applicable
          pricing.
        </p>
      </Section>

      <Section title="8. Third-party services">
        <p>
          The Service relies on third-party providers — including model providers such as
          OpenAI and cloud hosting and storage vendors — to operate. Your Content may be
          processed by those providers as described in our Privacy Policy. We are not
          responsible for third-party services we do not control.
        </p>
      </Section>

      <Section title="9. Intellectual property">
        <p>
          The Service — its software, design, documentation and trademarks — is owned by
          FlowBuddy and its licensors and is protected by intellectual-property law. Except
          for the rights expressly granted in these Terms, we reserve all rights. If you send
          us feedback or suggestions, you grant us the right to use them without obligation
          to you.
        </p>
      </Section>

      <Section title="10. Suspension and termination">
        <p>
          You may stop using the Service and request deletion of your account at any time. We
          may suspend or terminate your access if you materially breach these Terms, if
          required by law, or if continuing to provide the Service becomes impractical. On
          termination your licence to use the Service ends; sections that by their nature
          should survive (including 3, 4, 9, 11, 12 and 13) survive.
        </p>
      </Section>

      <Section title="11. Disclaimers">
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo;. TO THE
          FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED,
          INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT AND
          ANY WARRANTY THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE OR THAT GENERATED
          OUTPUT WILL BE ACCURATE.
        </p>
      </Section>

      <Section title="12. Limitation of liability">
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW, FLOWBUDDY WILL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF
          PROFITS, REVENUE, DATA OR GOODWILL, ARISING FROM OR RELATED TO THE SERVICE. OUR TOTAL
          LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF THE
          AMOUNTS YOU PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM OR ONE HUNDRED US DOLLARS
          (USD 100).
        </p>
      </Section>

      <Section title="13. Indemnity">
        <p>
          You will defend and indemnify FlowBuddy against claims, damages and costs
          (including reasonable legal fees) arising from Your Content, your use of the
          Service in breach of these Terms, or your violation of applicable law or of a third
          party&rsquo;s rights.
        </p>
      </Section>

      <Section title="14. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Material changes will be reflected by
          updating the &ldquo;Last updated&rdquo; date above and, where appropriate, by
          notifying you in the product or by email. Continuing to use the Service after a
          change takes effect means you accept the updated Terms.
        </p>
      </Section>

      <Section title="15. General">
        <p>
          These Terms are the entire agreement between you and FlowBuddy about the Service.
          If any provision is found unenforceable, the rest remains in effect. You may not
          assign these Terms without our consent; we may assign them in connection with a
          merger, acquisition or sale of assets. Our failure to enforce a provision is not a
          waiver of it.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these Terms? Email us at{' '}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="font-medium text-primary underline-offset-4 hover:underline"
          >
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </Section>
    </LegalPage>
  );
}
